extends Node3D

# --- 3D World Nodes ---
@onready var ai_clickable_area = $Control/CanvasLayer/UI_Control/Askbutton
@onready var  askbutton_status = true
@onready var player2 = $Control2/Player2
@onready var player = $Control2/Player
# --- UI Nodes ---
@onready var timer = $Timer
@onready var timer_label = $Control/CanvasLayer/UI_Control/TimerLabel

@onready var dialogue_label = $Control/CanvasLayer/UI_Control/DiaologueLabel

# The Question Menu UI
@onready var scroll_container = $Control/CanvasLayer/UI_Control/ScrollContainer
@onready var question_list = $Control/CanvasLayer/UI_Control/ScrollContainer/VBoxContainer
@onready var template_button = $Control/CanvasLayer/UI_Control/ScrollContainer/VBoxContainer/Button

@onready var questionsearch = $Control/CanvasLayer/UI_Control/HBoxContainer4/TextEdit
@onready var searchbtn = $Control/CanvasLayer/UI_Control/HBoxContainer4/Button

# The Guessing UI
@onready var guess_textbox = $Control/CanvasLayer/UI_Control/HBoxContainer3/TextEdit
@onready var guess_button = $Control/CanvasLayer/UI_Control/HBoxContainer3/Button

# The Job Menu UI
@onready var jobscroll_container = $Control/CanvasLayer/UI_Control/ScrollContainer2
@onready var job_list = $Control/CanvasLayer/UI_Control/ScrollContainer2/VBoxContainer
@onready var job_button = $Control/CanvasLayer/UI_Control/ScrollContainer2/VBoxContainer/Button

#@onready var joblabel = $CanvasLayer/UI_Control/answerlabel
@onready var restart = $Control/CanvasLayer/UI_Control/Button

@onready var pause_menu = $CanvasLayer2/Control
@onready var pausebtn = $Control/CanvasLayer/UI_Control/pausebtn
@onready var crossbtn = $CanvasLayer2/Control/crossbtn
@onready var restartbtn = $CanvasLayer2/Control/restart

@onready var resume = $CanvasLayer2/Control/resumebtn
@onready var home = $CanvasLayer2/Control/Home
@onready var help = $CanvasLayer2/Control/help
@onready var hidelabel= $CanvasLayer2/Control/Label2
@onready var tips= $CanvasLayer2/Control/tips
@onready var pauselabel = $CanvasLayer2/Control/Label
@onready var guessleft = $guessleft
@onready var scrollcontainter = $Control/CanvasLayer/UI_Control/ScrollContainer
# --- Game Variables ---
var game_data = {}
var current_ai_job = {}
var all_questions = []

# Tracker for remaining player guesses
var guesses_left: int = 15 

func _rand_val():
	var value = randf_range(0.3,0.7)
	return value

func get_random_color() -> Color:
	var random_hue = randf()
	return Color.from_hsv(random_hue, 1.0, 1.0)

func _ready():
	
	$Control2/Player2.get_active_material(0).albedo_color = get_random_color()
	$Control2/Player/Playercap.get_active_material(0).albedo_color = Color(1,1,0)
	var cap2_mat = $Control2/Player2/Playercap2.get_active_material(0).duplicate()
	cap2_mat.albedo_color = get_random_color()
	$Control2/Player2/Playercap2.set_surface_override_material(0, cap2_mat)
	restart.hide()
	pause_menu.hide()
	tips.hide()
	restart.pressed.connect(_on_restart_button_pressed)
	pausebtn.pressed.connect(_on_pausebtn_pressed)
	crossbtn.pressed.connect(_on_crossbtn_pressed)
	restartbtn.pressed.connect(_on_restart_button_pressed)
	resume.pressed.connect(_on_crossbtn_pressed)
	home.pressed.connect(_on_home_pressed)
	help.pressed.connect(_on_help_button_pressed)
	searchbtn.pressed.connect(_on_search_text_changed)
	
	var player1_material = $Control2/Player.get_active_material(0)

	if player1_material:
		# Duplicate the material so you don't accidentally change the color of every object sharing it
		var unique_material = player1_material.duplicate()
		
		# Set the new color (Using a random color generated by your existing function)
		unique_material.albedo_color = get_random_color() 
		
		# Override the surface material with your modified, unique material
		$Control2/Player.set_surface_override_material(0, unique_material)
	# Setup UI defaults
	scroll_container.hide() 
	template_button.hide()
	questionsearch.hide()
	searchbtn.hide()
	jobscroll_container.hide()
	job_button.hide()
	
	# Connect signals
	ai_clickable_area.pressed.connect(_on_3d_symbol_clicked)
	guess_button.pressed.connect(_on_guess_submitted)
	timer.timeout.connect(_on_timer_timeout)
	questionsearch.text_changed.connect(_on_search_text_changed) 
	guess_textbox.text_changed.connect(_on_guess_text_changed)
	
	load_json_data()
	if all_questions.size() > 0:
		start_new_round()

func _process(_delta):
	if not timer.is_stopped():
		var time_left = int(timer.time_left)
		var minutes = int(time_left) / 60
		var seconds = int(time_left) % 60
		
		# Separate UI text formatting for timer and guess limit labels
		timer_label.text = "%02d:%02d" % [minutes, seconds]
		guessleft.text = "Guesses Left: %d" % guesses_left
		#joblabel.text = current_ai_job["job_title"]
	if scroll_container.visible or jobscroll_container.visible :
		ai_clickable_area.hide()
	else:
		ai_clickable_area.show()

func _on_timer_timeout():
	timer_label.text = "00:00"
	game_over_lose("Time's up!")

func load_json_data():
	print("--- ATTEMPTING TO LOAD JSON ---")
	
	var path = "res://json/data.json" 
	if not FileAccess.file_exists(path):
		print("CRITICAL ERROR: Godot cannot find the file at: ", path)
		return
		
	var file = FileAccess.open(path, FileAccess.READ)
	if not file:
		print("CRITICAL ERROR: File exists, but Godot is blocked from opening it!")
		return
		
	var json_string = file.get_as_text()
	var json = JSON.new()
	var error = json.parse(json_string)
	
	if error != OK:
		print("CRITICAL ERROR: The JSON text is broken! Error at line ", json.get_error_line())
		return
		
	game_data = json.data
	if game_data.has("questions") and game_data.has("professions"):
		all_questions = game_data["questions"]
		print("SUCCESS: JSON loaded perfectly! ", all_questions.size(), " questions ready.")
	else:
		print("CRITICAL ERROR: JSON loaded, but it is missing the data we need!")

func start_new_round():
	var professions = game_data["professions"]
	current_ai_job = professions[randi() % professions.size()]
	
	# --- ADJUSTED DIFFICULTY CONFIGURATION ---
	if global.easy_state or (not global.easy_state and not global.mid_state and not global.hard_state):
		timer.wait_time = 300       # 5 minutes
		guesses_left = 15           
		dialogue_label.text = "You have 5 minutes and 15 guesses!"
	elif global.mid_state:
		timer.wait_time = 210       # 3 min 30 sec
		guesses_left = 7            
		dialogue_label.text = "You have 3:30 minutes and 7 guesses!"
	elif global.hard_state:
		timer.wait_time = 120       # 2 minutes
		guesses_left = 3            
		dialogue_label.text = "Watch out! You only have 
		2 minutes and 3 guesses!"

	timer.one_shot = true
	timer.start()

# ---------------------------------------------------------
# QUESTION MENU LOGIC
# ---------------------------------------------------------

func _on_3d_symbol_clicked():
	if timer.is_stopped(): return
	scroll_container.visible = !scroll_container.visible 
	dialogue_label.hide()
	if askbutton_status == false:
		ai_clickable_area.z_index = 3
		askbutton_status = false
	elif askbutton_status == true:
		ai_clickable_area.z_index =-1
		askbutton_status = true
	questionsearch.visible = scroll_container.visible
	searchbtn.visible = scroll_container.visible
	
	if scroll_container.visible:
		jobscroll_container.hide() 
		guess_textbox.text = ""
		questionsearch.text = "" 
		populate_questions("") 

func populate_questions(search_filter: String = ""):
	for child in question_list.get_children():
		if child != template_button:
			child.queue_free()
		
	for q in all_questions:
		var q_text_lower = q["text"].to_lower()
		var filter_lower = search_filter.to_lower()
		
		if filter_lower == "" or q_text_lower.contains(filter_lower):
			var new_btn = template_button.duplicate()
			new_btn.show() 
			new_btn.text = q["text"]
			new_btn.pressed.connect(_on_question_selected.bind(q["id"]))
			question_list.add_child(new_btn)

func _on_search_text_changed():
	var current_search = questionsearch.text.strip_edges()
	populate_questions(current_search)

func _on_question_selected(q_id):
	dialogue_label.show()
	scroll_container.hide()
	questionsearch.hide()
	searchbtn.hide()
	questionsearch.text = "" 
	
	if current_ai_job["answers"].has(q_id) and current_ai_job["answers"][q_id] != "":
		dialogue_label.text = current_ai_job["answers"][q_id]
	else:
		dialogue_label.text = "That doesn't really apply to my job."

# ---------------------------------------------------------
# JOB MENU LOGIC
# ---------------------------------------------------------

func populate_jobs(search_filter: String = ""):
	for child in job_list.get_children():
		if child != job_button:
			child.queue_free()
			
	var professions = game_data["professions"]
	for job in professions:
		var job_title = job["job_title"]
		var title_lower = job_title.to_lower()
		var filter_lower = search_filter.to_lower()
		
		if filter_lower == "" or title_lower.contains(filter_lower):
			var new_btn = job_button.duplicate()
			new_btn.show()
			new_btn.text = job_title
			new_btn.pressed.connect(_on_job_selected.bind(job_title))
			job_list.add_child(new_btn)

func _on_guess_text_changed():
	if timer.is_stopped(): return
	var current_search = guess_textbox.text.strip_edges()
	
	if current_search.length() > 0:
		jobscroll_container.show()
		scroll_container.hide()
		questionsearch.hide()
		searchbtn.hide()
	else:
		jobscroll_container.hide()
		
	populate_jobs(current_search)

func _on_job_selected(selected_job: String):
	jobscroll_container.hide()
	guess_textbox.text = ""
	dialogue_label.show()
	
	if timer.is_stopped(): 
		return 
		
	var actual_job = current_ai_job["job_title"].to_lower()
	
	if selected_job.to_lower() == actual_job:
		timer.stop() 
		dialogue_label.text = "Congrats you won! 
		I am a " + current_ai_job["job_title"] + "!"
		restart.show()
	else:
		# Deduct a guess count on failure
		guesses_left -= 1
		if guesses_left <= 0:
			guessleft.text = "Guesses Left: 0"
			game_over_lose("Out of guesses!")
		else:
			dialogue_label.text = "No, I'm not a " + selected_job + "! \n Keep guessing!"

func game_over_lose(reason: String):
	timer.stop()
	if current_ai_job.has("job_title"):
		dialogue_label.text = reason + " Game Over. 
		The job was: " + current_ai_job["job_title"]
	restart.show()

func _on_guess_submitted():
	if timer.is_stopped(): return
	#jobscroll_container.visible = !jobscroll_container.visible
	jobscroll_container.show()
	scroll_container.hide()
	questionsearch.hide()
	searchbtn.hide()
	
	# Manually trigger the job population with the current text
	var current_search = guess_textbox.text.strip_edges()
	populate_jobs(current_search)
	
	# Optional: Hide mobile keyboard after pressing search
	guess_textbox.release_focus()
func _on_restart_button_pressed():
	get_tree().reload_current_scene()

func _on_pausebtn_pressed():
	# Reset the inner pause menu visibility structure first
	pauselabel.show()
	help.show()
	restartbtn.show()
	home.show()
	resume.show()
	crossbtn.show()
	
	# Make sure the help items are safely turned off
	hidelabel.hide()
	tips.hide()
	
	# Finally, reveal the menu and pause
	pause_menu.show()
	$Timer.paused = true

func _on_crossbtn_pressed():
	pause_menu.hide()
	$Timer.paused = false
	
	# Reset layout states cleanly on close as well so nothing is stuck
	pauselabel.show()
	help.show()
	restartbtn.show()
	home.show()
	resume.show()
	hidelabel.hide()
	tips.hide()
	
func _on_home_pressed():
	get_tree().change_scene_to_file("res://scenes/main_menu.tscn")
	
func _on_help_button_pressed():
	help.hide()
	restart.hide()
	restartbtn.hide()
	home.hide()
	hidelabel.show()
	resume.hide()
	tips.show()
	crossbtn.show()
	pauselabel.hide()
